#!/usr/bin/env bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e
set -o pipefail
set -x

PACKAGES=$1
SHALLOW=${2:false}
JUSTDB=${3:false}
FORCE=${4:false}
EXTRACT_DIR=${5:-"$NEWROOT"}

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
source "${SCRIPT_ROOT}/eks-d-common"

if [ $JUSTDB ]; then
    JUSTDB="--justdb"
else
    JUSTDB=""
fi

RPMS=(${PACKAGES// / })
for rpm in "${RPMS[@]}"; do
    if [ ! $SHALLOW ]; then
        yum --installroot $NEWROOT install -y $rpm
    else
        yumdownloader --destdir=$DOWNLOAD_DIR -x "*.i686" $rpm
        rpm_file=$(ls $DOWNLOAD_DIR/$rpm-*.rpm)
        
        # if installed already skip
        if ! rpm --root $NEWROOT -q --quiet $rpm ; then
            rpm -ivh --nodeps --root $NEWROOT $JUSTDB $rpm_file
        fi       

        if [ $FORCE ]; then
            mkdir -p $EXTRACT_DIR
            pushd $EXTRACT_DIR
            rpm2cpio $rpm_file | cpio -idm
            popd
        fi
    fi
done
