#!/usr/bin/env bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -x
set -o errexit
set -o nounset
set -o pipefail

VARIANT="$1"

clean_docs $NEWROOT

clean_yum
rm -rf $DOWNLOAD_DIR $NEWROOT/var/lib/yum $NEWROOT/var/log/*.log $NEWROOT/var/tmp/rpm-tmp*

# al2202 build includes this folder during some rpm installs, removing since its a bad symlink
rm -rf $NEWROOT/usr/lib/.build-id

if [[ -n "${CLEANUP_UNNECESSARY_FILES:-}" ]]; then
    FILES=(${CLEANUP_UNNECESSARY_FILES// / })
    for f in ${FILES[@]}; do
        file=$NEWROOT$f
        if [ -f $file ]; then
            rm -f $file
        elif [ -L $file ]; then
            unlink $file
        fi
    done
fi

# generate final packages list
mkdir -p /tmp/packages
rpm --root $NEWROOT -qa | sort > /tmp/packages/$VARIANT
echo "*** FINAL PACKAGES FOR ${VARIANT^^} ***"
cat /tmp/packages/$VARIANT && \
echo "*******************************"
