#!/usr/bin/env bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -e
set -o pipefail
set -x

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
source "${SCRIPT_ROOT}/eks-d-common"

function build::install::deps() {
    local -r bin="$1"

    local rpm_package=""
    while IFS= read -r dep; do
        if build::common::dep_exists $dep; then
            continue
        fi
        
        rpm_package=$(build::common::rpm_package_for_binary $dep)

        if [[ -z "$rpm_package" ]]; then
            echo "Error: No rpm found for $dep!"
            exit 1
        fi

        echo "Installing $rpm_package for $dep"
        # install rpm with but do not install rpm dependencies, library deps will all be picked up
        # by this ldd parse
        clean_install $rpm_package true

    done < <(build::common::binary_to_libraries "$bin")
}

for installed_bin in "$@"; do
    if ! build::common::is_dynamic_binary $installed_bin; then
        continue
    fi

    build::install::deps $installed_bin
done
