#!/usr/bin/env bash
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -eE
set -o nounset
set -o pipefail

SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
source "${SCRIPT_ROOT}/eks-d-common"

echo "Validating all executables and libraries have all dependencies"

r_val=0
for bin in $(build::common::find_executables true); do
    if [[ $bin = /newroot/usr/lib64/gconv/* ]]; then
        # there are a number of libraries in this folder which are not validating
        # since all deps come along with them
        continue
    fi

    echo "----- Checking $bin   -----"    
    build::common::binary_to_libraries "$bin" "__libraries" > /dev/null 2>&1
    [ -z "${__libraries}" ] && continue
    while IFS= read -r c_dep; do
        if build::common::dep_exists "${c_dep}"; then
            continue
        fi
        echo "Missing DEP!!! ${c_dep}"
        r_val=1
           
    done < <(echo "${__libraries}")
    echo "----------------------------"
done

exit $r_val
