# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: releasechannels.distro.eks.amazonaws.com
spec:
  group: distro.eks.amazonaws.com
  names:
    kind: ReleaseChannel
    listKind: ReleaseChannelList
    plural: releasechannels
    singular: releasechannel
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The SNS Topic ARN for this release channel
      jsonPath: .spec.snsTopicARN
      name: TopicARN
      type: string
    - description: Indicates if this channel is active
      jsonPath: .status.active
      name: Active
      type: boolean
    - description: The latest release of this channel
      format: int32
      jsonPath: .status.latestRelease
      name: Latest Release
      type: integer
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ReleaseChannel is the Schema for the releasechannels API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ReleaseChannelSpec defines the desired state of ReleaseChannel
            properties:
              snsTopicARN:
                type: string
            type: object
          status:
            description: ReleaseChannelStatus defines the observed state of ReleaseChannel
            properties:
              active:
                type: boolean
              latestRelease:
                minimum: 1
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
