package constants

const (
	Aws                        = "aws"
	EksdBuildTooling           = "eks-distro-build-tooling"
	IssueAutocreatedTemplate   = "Issue was generated by eksGoTools createCveIssue, by:"
	EksGoSupportedVersionsPath = "projects/golang/go/MAINTAINED_EOL_VERSIONS"
)
