apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cherrypicker.serviceName }}
  namespace: default
spec:
  selector:
    app: cherrypicker
  ports:
  - port: 80
    targetPort: 8888
  type: ClusterIP
