kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crier
subjects:
- kind: ServiceAccount
  name: crier
  namespace: {{ .Release.Namespace }}