{{ if .Values.sinker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "sinker"
{{ end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sinker"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - delete
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - prow-sinker-leaderlock
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "sinker"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "sinker"
subjects:
- kind: ServiceAccount
  name: "sinker"
  namespace: {{ .Release.Namespace }}
