kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "tide"
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
      - get
      - watch