{{ if .Values.tide.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tide
{{ end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tide
rules:
  - apiGroups:
      - "prow.k8s.io"
    resources:
      - prowjobs
    verbs:
      - create
      - list
      - get
      - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tide
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tide
subjects:
- kind: ServiceAccount
  name: tide
  namespace: {{ .Release.Namespace }}
