# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Using one multistage Dockerfile since we use buildkit in prow
# there is no image repo so building images that build on each other 
# is not supported, unless we do a multistage build like the following
# where the caching system can be used for subsequent target builds

# *NOTE* we have to limit our number of layers heres because in presubmits there
# is no overlay fs and we will run out of space quickly

################# BUILDER ######################
ARG BASE_IMAGE
ARG BUILDER_IMAGE
FROM ${BUILDER_IMAGE} as base-docker-client-builder

RUN set -x && \
    # we only want the docker client cli and not the service
    # installing the package one off since the only deps of the client
    # are already provided by glibc
    amazon-linux-extras enable docker && \
    # has to be extracted instead of installed to work around scriptlet
    # issue that only affects the service component which we arent using
    clean_install docker true true true && \
    rm $NEWROOT/usr/bin/docker-* && \
    rm $NEWROOT/usr/bin/dockerd && \
    cleanup "docker"


################# DOCKER CLIENT ####################
FROM ${BASE_IMAGE} as base-docker-client
COPY --from=base-docker-client-builder /newroot /


################# EXPORT ######################
FROM scratch as base-docker-client-export
COPY --from=base-docker-client-builder /tmp/packages/* .
