# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Using one multistage Dockerfile since we use buildkit in prow
# there is no image repo so building images that build on each other 
# is not supported, unless we do a multistage build like the following
# where the caching system can be used for subsequent target builds

# *NOTE* we have to limit our number of layers heres because in presubmits there
# is no overlay fs and we will run out of space quickly

################# BUILDER ######################

#### Sketch alert ####
# We are pulling docker/container from al2 since it is not currently provided by al2022
# when al2022 adds these as packages we would want to switch asap
# Looking at the dependencies to the docker and containerd binaries, its really just libc
# From looking at upstream docs using a binary built against an older libc with a newer libc, which
# is what we would be doing here, *should* be ok
######################
ARG BASE_IMAGE
ARG BUILDER_IMAGE
ARG AL2_IMAGE
FROM ${AL2_IMAGE} as al2
RUN amazon-linux-extras enable docker


FROM ${BUILDER_IMAGE} as base-docker-client-builder

COPY --from=al2 /etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2 /etc/pki/rpm-gpg
COPY --from=al2 /etc/yum.repos.d/amzn2-extras.repo /etc/yum.repos.d

RUN set -x && \
    # we only want the docker client cli and not the service
    # installing the package one off since the only deps of the client
    # are already provided by glibc
    enable_docker_install && \
    # has to be extracted instead of installed to work around scriptlet
    # issue that only affects the service component which we arent using
    clean_install docker true true true && \
    rm $NEWROOT/usr/bin/docker-* && \
    rm $NEWROOT/usr/bin/dockerd && \
    cleanup "docker"


################# DOCKER CLIENT ####################
FROM ${BASE_IMAGE} as base-docker-client
COPY --from=base-docker-client-builder /newroot /


################# EXPORT ######################
FROM scratch as base-docker-client-export
COPY --from=base-docker-client-builder /tmp/packages/* .
