name: baseimage-pr-notifier
on:
  pull_request_target:
    types: [opened]
jobs:
  baseimage-pr-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and notify Slack
        run: |
          if [[ "${{ github.event.pull_request.title }}" == *"Update base image"* ]]; then
            curl -X POST $SLACK_WEBHOOK
            echo "Base image update detected - Slack notification sent"
          else
            echo "Not a base image update PR - Skipping notification"
          fi
          exit 0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
