name: Docker Check
on:
  pull_request:
    paths:
      - 'Dockerfile**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for ADD in Dockerfiles
        run: |
          if grep 'ADD ' -r ./* | grep Docker; then
            echo "check_result=true" >> $GITHUB_OUTPUT
          else
            echo "check_result=false" >> $GITHUB_OUTPUT
          fi